### ISSUE TITLE
Quartz.net

### ISSUE THREAD

**Issue by ainux4mrvce** [wbf1013/wbf1013.github.io#23]
i have a fuelUI Scheduler control on web page,
![image](https://cloud.githubusercontent.com/assets/5284414/13599920/b4af7bd0-e54b-11e5-8243-f29052a2a554.png)

using service stack i am collecting all the scheduling information need to schedule a job from this page, and also have a method which converts the time into cron expression as i am using cron. can some on evaluate this code or if you enhance this code.

source code:

**
> public string getCronPattern(RecurrencePattern recurrencePattern, TimeSpan time)
>         {
> 
>             string cronPattern = string.Empty;
>             if (recurrencePattern.FREQ == "DAILY")
>             {
>                 if (recurrencePattern.BYDAY != null)
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " 1/" + recurrencePattern.INTERVAL + " * " + recurrencePattern.BYDAY + " * *";
>                 else
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " 1/" + recurrencePattern.INTERVAL + " * ? *";
>             }
>             else if (recurrencePattern.FREQ == "HOURLY")
>             {
>                 cronPattern = "0 " + time.Minutes + " " + time.Hours + "/" + recurrencePattern.INTERVAL + " * * ? *";
>             }
>             else if (recurrencePattern.FREQ == "WEEKLY")
>             {
>                 cronPattern = "0 " + time.Minutes + " " + time.Hours + " ? * " + recurrencePattern.BYDAY + " *";
>             }
>             else if (recurrencePattern.FREQ == "MONTHLY")
>             {
>                 if (recurrencePattern.BYMONTHDAY > 0)
>                     cronPattern = " 0 " + time.Minutes + " " + time.Hours + " " + recurrencePattern.BYMONTHDAY + " 1/1 ? *";
>                 else
>                     cronPattern = "0 " + time.Minutes + " " + time.Hours + " ? 1/1 " + recurrencePattern.BYDAY + "#" + recurrencePattern.BYSETPOS + " *";
>             }
>             else
>             {
>                 if (recurrencePattern.BYDAY != null)
>                     cronPattern = "0 0 12 ? " + recurrencePattern.BYMONTH + " " + recurrencePattern.BYDAY + "#" + recurrencePattern.BYSETPOS + " *";
>                 else
>                     cronPattern = "0 0 12 " + recurrencePattern.BYMONTHDAY + " " + recurrencePattern.BYMONTH + " ? *";
>             }
>             return cronPattern;
> 
>         }**

**Comment by wbf1013** [comment]
This issue does not appear relevant to My blog. Perhaps it was accidentally opened against the wrong project? Closing.

**Comment by ainux4mrvce** [comment]
As i seen that, in your last blog your talking about the cron expression so i upload this code which i use to extract input from user input and converting into cron expression before passing it into trigger ..!!

**Comment by wbf1013** [comment]
so you want me to check the code, and enhance the code ?

**Comment by ainux4mrvce** [comment]
ya kind of if you are still working on this module plz.

**Comment by wbf1013** [comment]
you can write code like  this, less if  more other way,   simple and clean,  write once , call everywhere .
remember  one corn expression  contains 6 or 7 part . 
```
public string getCronPattern(RecurrencePattern recurrencePattern, TimeSpan time) {
    string cronPattern = string.Empty;
    switch (recurrencePattern.FREQ) {
        case "DAILY":
            cronPattern = "0 " + time.Minutes + " " + time.Hours + " 1/" + recurrencePattern.INTERVAL + " * " + (recurrencePattern.BYDAY != null ? recurrencePattern.BYDAY : "?") + " *";
            break;
        case "HOURLY":
            cronPattern = "0 " + time.Minutes + " " + time.Hours + "/" + recurrencePattern.INTERVAL + " * * ? *";
            break;
        case "WEEKLY":
            cronPattern = "0 " + time.Minutes + " " + time.Hours + " ? * " + recurrencePattern.BYDAY + " *";
            break;
        case "MONTHLY":
            cronPattern = " 0 " + time.Minutes + " " + time.Hours + " " + recurrencePattern.BYMONTHDAY != null + " 1/1 ? *";
            break;
        default:
            ...
            break; 
    }

    return cronPattern;
}
```

**Comment by ainux4mrvce** [comment]
@wbf1013  thanx i was thinking about switch case but really needed some one to advice me thanx a lot
